return {
	diagnostic = {
		error = "",
		warn = "",
		info = "󰋼",
		hint = "󰌵",
		error_neg = "",
		warn_neg = "",
		hint_neg = "",
		info_neg = "",
	},
	lualine = {
		modified = "",
		readonly = "",
		unnamed = "",
		newfile = "",
		lsp = "",
	},
	git = {
		added = "",
		modified = "",
		removed = "",
		gitbar = "┃",
	},
	folds = {
		foldopen = "",
		foldclose = "",
		foldline_fill = "",
		foldsep = " ",
	},
	whichkey = {
		buffer = "",
		explorer = "󱏒",
		undotree = "󰕍",
		history = "",
		language = "",
		config = "",
		packages = "",
		extras = "",
		home = "",
		cd = "",
		math = "󰒠",
		right = "󱦰",
		left = "󱦱",
		top = "",
		bottom = "",
		center = "󰘢",
		list = "󰉹",
		ai = "󱚡",
		markdown = "",
	},
	debug = {
		bug = "",
		breakpoint = "",
		conditional = "",
		logpoint = "",
		stopped = "",
		rejected = "󰐼",
	},
	lazy = {
		cmd = "  ",
		config = "  ",
		event = "  ",
		ft = "  ",
		init = "  ",
		imports = "  ",
		keys = "  ",
		lazy = " ",
		loaded = " ",
		not_loaded = " ",
		plugin = "  ",
		runtime = "  ",
		require = "  ",
		source = " ",
		start = "",
		task = "  ",
	},
}
