-- vim.api.nvim_set_hl(0, "RenderMarkdownCode", { bg = "NONE", fg = "NONE" })
vim.api.nvim_set_hl(0, "LspSignatureActiveParameter", { italic = true, bold = true })
vim.api.nvim_set_hl(0, "SnacksPickerPathIgnored", { link = "Ignore" })
vim.api.nvim_set_hl(0, "SnacksPickerGitStatussdfIgnored", { link = "Ignore" })
vim.api.nvim_set_hl(0, "RenderMarkdownH1Bg", { link = "DiffAdd" })
vim.api.nvim_set_hl(0, "RenderMarkdownH2Bg", { link = "DiffChange" })
vim.api.nvim_set_hl(0, "RenderMarkdownH3Bg", { link = "DiffDelete" })
vim.api.nvim_set_hl(0, "SniprunVirtualTextOk", { link = "Grey" })
vim.api.nvim_set_hl(0, "SniprunVirtualTextErr", { link = "Red" })
vim.api.nvim_set_hl(0, "DiffText", { link = "DiffChange" })
