# vim:fileencoding=utf-8:foldmethod=marker

# Fonts {{{

# BEGIN_KITTY_FONTS
font_family      family='Cascadia Mono NF' style=Regular variable_name=CascadiaMonoNFRoman
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS

font_size 11.0

# }}}

# Cursor {{{

cursor_trail 5

# }}}

# Clipboard {{{ 

clear_selection_on_clipboard_loss yes
map ctrl+v paste_from_clipboard
map ctrl+c copy_or_noop

# }}}

# UI {{{

background_opacity 0.95
sync_to_monitor no
map ctrl+kp_add change_font_size all +1.0
map ctrl+minus change_font_size all -1.0

# }}}
