[ai]
rules = ""
[ai.google]

[ai.anthropic]

[ai.open_ai]

[formatting]
line_length = 90

[runtime]
output_max_bytes = 8000000
reactive_tests = true
std_stream_max_bytes = 1000000
auto_instantiate = false
on_cell_change = "lazy"
auto_reload = "lazy"
watcher_on_save = "lazy"

[language_servers.pylsp]
enable_pyflakes = false
enable_pydocstyle = false
enable_flake8 = false
enable_ruff = true
enable_pylint = false
enabled = false
enable_mypy = true

[keymap]
preset = "vim"
[keymap.overrides]
"global.commandPalette" = "Ctrl-Shift-p"

[package_management]
manager = "uv"

[server]
follow_symlink = false
browser = "default"

[display]
cell_output = "below"
dataframes = "rich"
default_width = "medium"
default_table_page_size = 10
code_editor_font_size = 14
theme = "system"

[save]
autosave_delay = 1000
autosave = "off"
format_on_save = false

[snippets]
custom_paths = []
include_default_snippets = true

[completion]
activate_on_typing = true
copilot = false

[diagnostics]
enabled = false
