gui:
  nerdFontsVersion: 3
  spinner:
    frames:
      - ⠙
      - ⠹
      - ⠸
      - ⠼
      - ⠴
      - ⠦
      - ⠧
      - ⠇
      - ⠏
      - ⠋
    rate: 50
  showRootItemInFileTree: true
  switchTabsWithPanelJumpKeys: true
os:
  edit: nvim -- {{filename}}
  editAtLine: nvim +{{line}} -- {{filename}}
  editAtLineAndWait: nvim +{{line}} -- {{filename}}
  openDirInEditor: nvim -- {{dir}}
disableStartupPopups: true
promptToReturnFromSubprocess: false
notARepository: prompt
