[[mgr.prepend_keymap]]
on = "q"
run = "quit --no-cwd-file"
desc = "quit"

[[mgr.prepend_keymap]]
on = "Q"
run = "quit"
desc = "quit and cd"

[[mgr.prepend_keymap]]
on = "?"
run = "help"
desc = "help"

[[mgr.prepend_keymap]]
on = "<Enter>"
run = "plugin smart-enter"
desc = "Enter the child directory, or open the file"

[[mgr.prepend_keymap]]
on = "l"
run = "plugin smart-enter"
desc = "Enter the child directory, or open the file"

[[mgr.prepend_keymap]]
on = "T"
run = "plugin smart-tab"
desc = "Create a tab and enter the hovered directory"

[[mgr.prepend_keymap]]
on = ["t", "q"]
run = "close"
desc = "Close the current tab, or quit if it's last"

[[mgr.prepend_keymap]]
on = "<C-n>"
run = "seek 5"
desc = "Scroll down in preview"

[[mgr.prepend_keymap]]
on = "<C-p>"
run = "seek -5"
desc = "Scroll up in preview"

[[help.prepend_keymap]]
on = "q"
run = "close"
desc = "close help"

[[help.prepend_keymap]]
on = "/"
run = "filter"

[[help.prepend_keymap]]
on = "d"
run = "arrow 50%"

[[help.prepend_keymap]]
on = "u"
run = "arrow -50%"

[[input.prepend_keymap]]
on = "<Esc>"
run = "close"
desc = "Cancel input"
