[mgr]
sort_sensitive = false
show_hidden = false
linemode = "size_and_mtime"
scrolloff = 4

[plugin]
prepend_previewers = [
  { url = "*.ipynb", run = 'piper -- nbpreview --no-paging --nerd-font --decorated --no-files --unicode --color --images --color-system=standard --theme=ansi_dark "$1"' },
  { url = "*.h5", run = 'piper -- h5ls "$1"' },
  { url = "*.csv", run = 'piper -- echo "N rows: " && xan count "$1" && echo "" && xan flatten "$1" -l 1 && echo "" && xan stats "$1" | xan view -s type,count,mean' }
]
prepend_fetchers = [
  { url = "*", run = "git", group = "git" },
  { url = "*/", run = "git", group = "git" }
]

[opener]
edit = [
  { run = "$EDITOR %s", block = true, desc = "$EDITOR", for = "unix" },
  { run = "%EDITOR% %s", block = true, desc = "%EDITOR%", for = "windows" },
]
open = [
  { run = "csvlens --colorful %s", block = true, for = "unix", desc = "csvlens" },
]

[open]
prepend_rules = [
  { url = "*.csv", use = ["open", "edit"] },
]

[preview]
tab_size = 2
