return {}

-- local util = require("vim.lsp.util")
-- -- The function that replace those quirky html symbols.
-- local function split_lines(value)
-- 	value = string.gsub(value, "&nbsp;", " ")
-- 	value = string.gsub(value, "&gt;", ">")
-- 	value = string.gsub(value, "&lt;", "<")
-- 	value = string.gsub(value, "\\", "")
-- 	return vim.split(value, "\n", { plain = true, trimempty = true })
-- end
--
-- local function insert_plaintextquotes(contents)
-- 	local in_code_block = false
-- 	for i, line in ipairs(contents) do
-- 		if line:match("^```") then
-- 			in_code_block = not in_code_block
-- 		elseif not in_code_block then
-- 			table.insert(contents, i + 1, "```")
-- 			break
-- 		end
-- 	end
-- 	table.insert(contents, "```")
-- 	return contents
-- end
--
-- local function convert_input_to_markdown_lines(input, contents)
-- 	contents = contents or {}
-- 	assert(type(input) == "table", "Expected a table for LSP input")
-- 	if input.kind then
-- 		local value = input.value or ""
-- 		vim.list_extend(contents, split_lines(value))
-- 		-- contents = insert_plaintextquotes(contents)
-- 	end
-- 	if (contents[1] == "" or contents[1] == nil) and #contents == 1 then
-- 		return {}
-- 	end
-- 	return contents
-- end
--
-- -- The overwritten hover function that pyright uses.
-- -- Note that other language server can use the default one.
-- local function hover(_, result, ctx, config)
-- 	config = config or {}
-- 	config.focus_id = ctx.method
-- 	if vim.api.nvim_get_current_buf() ~= ctx.bufnr then
-- 		-- Ignore result since buffer changed. This happens for slow language servers.
-- 		return
-- 	end
-- 	if not (result and result.contents) then
-- 		if config.silent ~= true then
-- 			vim.notify("No information available")
-- 		end
-- 		return
-- 	end
-- 	local contents ---@type string[]
-- 	contents = convert_input_to_markdown_lines(result.contents)
-- 	if vim.tbl_isempty(contents) then
-- 		if config.silent ~= true then
-- 			vim.notify("No information available")
-- 		end
-- 		return
-- 	end
-- 	-- Notice here. The "plaintext" string was originally "markdown".
-- 	-- The reason of using "plaintext" instead of "markdown" is becasue
-- 	-- of the bracket characters ([]). Markdown will hide single bracket,
-- 	-- so when your docstrings consist of numpy or pytorch or python list,
-- 	-- you will get garbadge hover results.
-- 	-- The bad side of "plaintext" is that you never get syntax highlighting.
-- 	-- I personally don't care about this.
-- 	return util.open_floating_preview(contents, "markdown", config)
-- end
--
-- ---@type LazySpec
-- return {
-- 	"AstroNvim/astrolsp",
-- 	---@type AstroLSPOpts
-- 	opts = {
-- 		handlers = {
-- 			-- Default handler
-- 			function(server, opts)
-- 				require("lspconfig")[server].setup(opts)
-- 			end,
-- 			basedpyright = function(_, opts)
-- 				opts.handlers = {
-- 					["textDocument/hover"] = vim.lsp.with(hover, {
-- 						border = "rounded",
-- 					}),
-- 				}
-- 				require("lspconfig").basedpyright.setup(opts)
-- 			end,
-- 		},
-- 	},
-- }
