#!/usr/bin/env bash

# Switch to vim bindings
set -g mode-keys vi
set -g status-keys vi

# Mouse on
set -g mouse on

# Terminal titles
set-option -g set-titles on
set-option -g set-titles-string "#h #S: #W"

# Colors
set -g default-terminal "tmux-256color"
set-option -sa terminal-overrides ",xterm-256color:RGB"
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'  # undercurl support
set -as terminal-overrides ',*:Setulc=\E[58::2::::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'  # underscore colours - needs tmux-3.0 colors

# keymaps
set -sg escape-time 0
bind h split-window -h -c "#{pane_current_path}" \; display-pane -b -d 200 
bind v split-window -v -c "#{pane_current_path}" \; display-pane -b -d 200 

# Increase tmux messages display duration from 750ms to 4s
set -g display-time 4000
set -g focus-events on

# Clipboard
set -s set-clipboard on

# Status bar
set -g status on
set -g status-style 'bg=default'
set -g status-interval 1

set -g window-status-format " #I:#{s|$HOME||:pane_current_path}$#[italics]#W "
set -g window-status-current-format "#[fg=default][#[fg=green]#I:#{s|$HOME||:pane_current_path}$#[italics]#W#[fg=default]]"
set -g status-justify centre
set -g status-left '#h [#S:#I:#P] '
set -g status-left-length 30
set -g status-right '%H:%M:%S'

# Plugins
set -g @plugin "tmux-plugins/tpm"
set -g @plugin "tmux-plugins/tmux-resurrect"
set -g @plugin "tmux-plugins/tmux-continuum"
set -g @plugin "aserowy/tmux.nvim" 	

if "test ! -d ~/.config/tmux/plugins/tpm" \
   "run 'git clone https://github.com/tmux-plugins/tpm ~/.config/tmux/plugins/tpm && ~/.config/tmux/plugins/tpm/bin/install_plugins'"

run '~/.config/tmux/plugins/tpm/tpm'

