# Switch to vim bindings
set -g mode-keys vi
set -g status-keys vi

# Mouse on
set -g mouse on

# Terminal titles
set-option -g set-titles on
set-option -g set-titles-string "#h #S: #W"

# colors... doesnt do anything?
set -g default-terminal "tmux-256color"
set-option -sa terminal-overrides ",xterm-256color:RGB"

# keymaps
set -sg escape-time 0
bind -n M-l select-pane -L \; display-pane -b -d 200 
bind -n M-h select-pane -R \; display-pane -b -d 200 
bind -n M-k select-pane -U \; display-pane -b -d 200 
bind -n M-j select-pane -D \; display-pane -b -d 200 
bind -n M-left select-pane -L \; display-pane -b -d 200 
bind -n M-right select-pane -R \; display-pane -b -d 200 
bind -n M-up select-pane -U \; display-pane -b -d 200 
bind -n M-down select-pane -D \; display-pane -b -d 200 
bind h split-window -h -c "#{pane_current_path}" \; display-pane -b -d 200 
bind v split-window -v -c "#{pane_current_path}" \; display-pane -b -d 200 

# Window sizing
set aggressive-resize off
set window-size latest

# Increase tmux messages display duration from 750ms to 4s
set -g display-time 4000
set -g focus-events on

# Clipboard
set -s set-clipboard on

# History size
set history-limit 25000

# Plugins
set -g @plugin "tmux-plugins/tpm"
set -g @plugin "tmux-plugins/tmux-resurrect"
# set -g @plugin "tmux-plugins/tmux-continuum"
# set -g @continuum-restore "on"

run '~/.config/tmux/plugins/tpm/tpm'

# Status bar
set -g status on
set -g status-style 'bg=default'
set -g status-interval 1

set -g window-status-format " #I:#{s|$HOME||:pane_current_path}$#[italics]#W "
set -g window-status-current-format "#[fg=default][#[fg=green]#I:#{s|$HOME||:pane_current_path}$#[italics]#W#[fg=default]]"
set -g status-justify centre
set -g status-left '#h [#S:#I:#P] '
set -g status-left-length 30
set -g status-right '%H:%M:%S'

# if -F '#{!=:#{status},2}' {
#     set -Fg 'status-format[1]' '#{status-format[0]}'
#     set -g 'status-format[0]' '#[bg=default]'
#     set -g status 2
# }
